/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedViaturasRouteImport } from './routes/_authenticated/viaturas'
import { Route as AuthenticatedImprimirIdRouteImport } from './routes/_authenticated/imprimir.$id'
import { Route as AuthenticatedOcorrenciasIdRouteImport } from './routes/_authenticated/ocorrencias.$id'
import { Route as AuthenticatedOcorrenciasNovaRouteImport } from './routes/_authenticated/ocorrencias.nova'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedViaturasRoute = AuthenticatedViaturasRouteImport.update({
  id: '/viaturas',
  path: '/viaturas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImprimirIdRoute = AuthenticatedImprimirIdRouteImport.update({
  id: '/imprimir/$id',
  path: '/imprimir/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOcorrenciasIdRoute =
  AuthenticatedOcorrenciasIdRouteImport.update({
    id: '/ocorrencias/$id',
    path: '/ocorrencias/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOcorrenciasNovaRoute =
  AuthenticatedOcorrenciasNovaRouteImport.update({
    id: '/ocorrencias/nova',
    path: '/ocorrencias/nova',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/viaturas': typeof AuthenticatedViaturasRoute
  '/imprimir/$id': typeof AuthenticatedImprimirIdRoute
  '/ocorrencias/$id': typeof AuthenticatedOcorrenciasIdRoute
  '/ocorrencias/nova': typeof AuthenticatedOcorrenciasNovaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/viaturas': typeof AuthenticatedViaturasRoute
  '/imprimir/$id': typeof AuthenticatedImprimirIdRoute
  '/ocorrencias/$id': typeof AuthenticatedOcorrenciasIdRoute
  '/ocorrencias/nova': typeof AuthenticatedOcorrenciasNovaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/viaturas': typeof AuthenticatedViaturasRoute
  '/_authenticated/imprimir/$id': typeof AuthenticatedImprimirIdRoute
  '/_authenticated/ocorrencias/$id': typeof AuthenticatedOcorrenciasIdRoute
  '/_authenticated/ocorrencias/nova': typeof AuthenticatedOcorrenciasNovaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/painel'
    | '/perfil'
    | '/relatorios'
    | '/usuarios'
    | '/viaturas'
    | '/imprimir/$id'
    | '/ocorrencias/$id'
    | '/ocorrencias/nova'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/painel'
    | '/perfil'
    | '/relatorios'
    | '/usuarios'
    | '/viaturas'
    | '/imprimir/$id'
    | '/ocorrencias/$id'
    | '/ocorrencias/nova'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/painel'
    | '/_authenticated/perfil'
    | '/_authenticated/relatorios'
    | '/_authenticated/usuarios'
    | '/_authenticated/viaturas'
    | '/_authenticated/imprimir/$id'
    | '/_authenticated/ocorrencias/$id'
    | '/_authenticated/ocorrencias/nova'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/viaturas': {
      id: '/_authenticated/viaturas'
      path: '/viaturas'
      fullPath: '/viaturas'
      preLoaderRoute: typeof AuthenticatedViaturasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/imprimir/$id': {
      id: '/_authenticated/imprimir/$id'
      path: '/imprimir/$id'
      fullPath: '/imprimir/$id'
      preLoaderRoute: typeof AuthenticatedImprimirIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ocorrencias/$id': {
      id: '/_authenticated/ocorrencias/$id'
      path: '/ocorrencias/$id'
      fullPath: '/ocorrencias/$id'
      preLoaderRoute: typeof AuthenticatedOcorrenciasIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ocorrencias/nova': {
      id: '/_authenticated/ocorrencias/nova'
      path: '/ocorrencias/nova'
      fullPath: '/ocorrencias/nova'
      preLoaderRoute: typeof AuthenticatedOcorrenciasNovaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedViaturasRoute: typeof AuthenticatedViaturasRoute
  AuthenticatedImprimirIdRoute: typeof AuthenticatedImprimirIdRoute
  AuthenticatedOcorrenciasIdRoute: typeof AuthenticatedOcorrenciasIdRoute
  AuthenticatedOcorrenciasNovaRoute: typeof AuthenticatedOcorrenciasNovaRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedViaturasRoute: AuthenticatedViaturasRoute,
  AuthenticatedImprimirIdRoute: AuthenticatedImprimirIdRoute,
  AuthenticatedOcorrenciasIdRoute: AuthenticatedOcorrenciasIdRoute,
  AuthenticatedOcorrenciasNovaRoute: AuthenticatedOcorrenciasNovaRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
