/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedEscalasRouteImport } from './routes/_authenticated/escalas'
import { Route as AuthenticatedEquipeRouteImport } from './routes/_authenticated/equipe'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedPostosRouteImport } from './routes/_authenticated/postos'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedViaturasRouteImport } from './routes/_authenticated/viaturas'
import { Route as AuthenticatedImprimirIdRouteImport } from './routes/_authenticated/imprimir.$id'
import { Route as AuthenticatedOcorrenciasIdRouteImport } from './routes/_authenticated/ocorrencias.$id'
import { Route as AuthenticatedOcorrenciasNovaRouteImport } from './routes/_authenticated/ocorrencias.nova'
import { Route as AuthenticatedPlantaoRouteImport } from './routes/_authenticated/plantao'
import { Route as AuthenticatedPlantaoIdRouteImport } from './routes/_authenticated/plantao.$id'
import { Route as AuthenticatedRelatorioPdfIdRouteImport } from './routes/_authenticated/relatorio-pdf.$id'
import { Route as AuthenticatedItensArmasRouteImport } from './routes/_authenticated/itens-armas'
import { Route as AuthenticatedItensRadiosRouteImport } from './routes/_authenticated/itens-radios'
import { Route as AuthenticatedItensCadRouteImport } from './routes/_authenticated/itens-cad'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEscalasRoute = AuthenticatedEscalasRouteImport.update({
  id: '/escalas',
  path: '/escalas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEquipeRoute = AuthenticatedEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPostosRoute = AuthenticatedPostosRouteImport.update({
  id: '/postos',
  path: '/postos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedViaturasRoute = AuthenticatedViaturasRouteImport.update({
  id: '/viaturas',
  path: '/viaturas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImprimirIdRoute = AuthenticatedImprimirIdRouteImport.update({
  id: '/imprimir/$id',
  path: '/imprimir/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOcorrenciasIdRoute =
  AuthenticatedOcorrenciasIdRouteImport.update({
    id: '/ocorrencias/$id',
    path: '/ocorrencias/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOcorrenciasNovaRoute =
  AuthenticatedOcorrenciasNovaRouteImport.update({
    id: '/ocorrencias/nova',
    path: '/ocorrencias/nova',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlantaoRoute = AuthenticatedPlantaoRouteImport.update({
  id: '/plantao',
  path: '/plantao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedItensArmasRoute = AuthenticatedItensArmasRouteImport.update({
  id: '/itens-armas', path: '/itens-armas', getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedItensRadiosRoute = AuthenticatedItensRadiosRouteImport.update({
  id: '/itens-radios', path: '/itens-radios', getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedItensCadRoute = AuthenticatedItensCadRouteImport.update({
  id: '/itens-cad', path: '/itens-cad', getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlantaoIdRoute = AuthenticatedPlantaoIdRouteImport.update({
  id: '/plantao/$id',
  path: '/plantao/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatorioPdfIdRoute = AuthenticatedRelatorioPdfIdRouteImport.update({
  id: '/relatorio-pdf/$id',
  path: '/relatorio-pdf/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/escalas': typeof AuthenticatedEscalasRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/postos': typeof AuthenticatedPostosRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/viaturas': typeof AuthenticatedViaturasRoute
  '/imprimir/$id': typeof AuthenticatedImprimirIdRoute
  '/ocorrencias/$id': typeof AuthenticatedOcorrenciasIdRoute
  '/ocorrencias/nova': typeof AuthenticatedOcorrenciasNovaRoute
  '/itens-armas': typeof AuthenticatedItensArmasRoute
  '/itens-radios': typeof AuthenticatedItensRadiosRoute
  '/itens-cad': typeof AuthenticatedItensCadRoute
  '/plantao': typeof AuthenticatedPlantaoRoute
  '/plantao/$id': typeof AuthenticatedPlantaoIdRoute
  '/relatorio-pdf/$id': typeof AuthenticatedRelatorioPdfIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/escalas': typeof AuthenticatedEscalasRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/postos': typeof AuthenticatedPostosRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/viaturas': typeof AuthenticatedViaturasRoute
  '/imprimir/$id': typeof AuthenticatedImprimirIdRoute
  '/ocorrencias/$id': typeof AuthenticatedOcorrenciasIdRoute
  '/ocorrencias/nova': typeof AuthenticatedOcorrenciasNovaRoute
  '/itens-armas': typeof AuthenticatedItensArmasRoute
  '/itens-radios': typeof AuthenticatedItensRadiosRoute
  '/itens-cad': typeof AuthenticatedItensCadRoute
  '/plantao/$id': typeof AuthenticatedPlantaoIdRoute
  '/relatorio-pdf/$id': typeof AuthenticatedRelatorioPdfIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/escalas': typeof AuthenticatedEscalasRoute
  '/_authenticated/equipe': typeof AuthenticatedEquipeRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/postos': typeof AuthenticatedPostosRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/viaturas': typeof AuthenticatedViaturasRoute
  '/_authenticated/imprimir/$id': typeof AuthenticatedImprimirIdRoute
  '/_authenticated/ocorrencias/$id': typeof AuthenticatedOcorrenciasIdRoute
  '/_authenticated/ocorrencias/nova': typeof AuthenticatedOcorrenciasNovaRoute
  '/_authenticated/itens-armas': typeof AuthenticatedItensArmasRoute
  '/_authenticated/itens-radios': typeof AuthenticatedItensRadiosRoute
  '/_authenticated/itens-cad': typeof AuthenticatedItensCadRoute
  '/_authenticated/plantao': typeof AuthenticatedPlantaoRoute
  '/_authenticated/plantao/$id': typeof AuthenticatedPlantaoIdRoute
  '/_authenticated/relatorio-pdf/$id': typeof AuthenticatedRelatorioPdfIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/escalas'
    | '/equipe'
    | '/historico'
    | '/painel'
    | '/perfil'
    | '/postos'
    | '/relatorios'
    | '/usuarios'
    | '/viaturas'
    | '/imprimir/$id'
    | '/ocorrencias/$id'
    | '/ocorrencias/nova'
    | '/itens-armas'
    | '/itens-radios'
    | '/itens-cad'
    | '/plantao'
    | '/plantao/$id'
    | '/relatorio-pdf/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/escalas'
    | '/equipe'
    | '/historico'
    | '/painel'
    | '/perfil'
    | '/postos'
    | '/relatorios'
    | '/usuarios'
    | '/viaturas'
    | '/imprimir/$id'
    | '/ocorrencias/$id'
    | '/ocorrencias/nova'
    | '/itens-armas'
    | '/itens-radios'
    | '/itens-cad'
    | '/plantao'
    | '/plantao/$id'
    | '/relatorio-pdf/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/escalas'
    | '/_authenticated/equipe'
    | '/_authenticated/historico'
    | '/_authenticated/painel'
    | '/_authenticated/perfil'
    | '/_authenticated/postos'
    | '/_authenticated/relatorios'
    | '/_authenticated/usuarios'
    | '/_authenticated/viaturas'
    | '/_authenticated/imprimir/$id'
    | '/_authenticated/ocorrencias/$id'
    | '/_authenticated/ocorrencias/nova'
    | '/_authenticated/plantao/$id'
    | '/_authenticated/relatorio-pdf/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/equipe': {
      id: '/_authenticated/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AuthenticatedEquipeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/escalas': {
      id: '/_authenticated/escalas'
      path: '/escalas'
      fullPath: '/escalas'
      preLoaderRoute: typeof AuthenticatedEscalasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/postos': {
      id: '/_authenticated/postos'
      path: '/postos'
      fullPath: '/postos'
      preLoaderRoute: typeof AuthenticatedPostosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/viaturas': {
      id: '/_authenticated/viaturas'
      path: '/viaturas'
      fullPath: '/viaturas'
      preLoaderRoute: typeof AuthenticatedViaturasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/imprimir/$id': {
      id: '/_authenticated/imprimir/$id'
      path: '/imprimir/$id'
      fullPath: '/imprimir/$id'
      preLoaderRoute: typeof AuthenticatedImprimirIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ocorrencias/$id': {
      id: '/_authenticated/ocorrencias/$id'
      path: '/ocorrencias/$id'
      fullPath: '/ocorrencias/$id'
      preLoaderRoute: typeof AuthenticatedOcorrenciasIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ocorrencias/nova': {
      id: '/_authenticated/ocorrencias/nova'
      path: '/ocorrencias/nova'
      fullPath: '/ocorrencias/nova'
      preLoaderRoute: typeof AuthenticatedOcorrenciasNovaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plantao': {
      id: '/_authenticated/plantao'
      path: '/plantao'
      fullPath: '/plantao'
      preLoaderRoute: typeof AuthenticatedPlantaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/itens-armas': {
      id: '/_authenticated/itens-armas'
      path: '/itens-armas'
      fullPath: '/itens-armas'
      preLoaderRoute: typeof AuthenticatedItensArmasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/itens-radios': {
      id: '/_authenticated/itens-radios'
      path: '/itens-radios'
      fullPath: '/itens-radios'
      preLoaderRoute: typeof AuthenticatedItensRadiosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/itens-cad': {
      id: '/_authenticated/itens-cad'
      path: '/itens-cad'
      fullPath: '/itens-cad'
      preLoaderRoute: typeof AuthenticatedItensCadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plantao/$id': {
      id: '/_authenticated/plantao/$id'
      path: '/plantao/$id'
      fullPath: '/plantao/$id'
      preLoaderRoute: typeof AuthenticatedPlantaoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorio-pdf/$id': {
      id: '/_authenticated/relatorio-pdf/$id'
      path: '/relatorio-pdf/$id'
      fullPath: '/relatorio-pdf/$id'
      preLoaderRoute: typeof AuthenticatedRelatorioPdfIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedEscalasRoute: typeof AuthenticatedEscalasRoute
  AuthenticatedEquipeRoute: typeof AuthenticatedEquipeRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedPostosRoute: typeof AuthenticatedPostosRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedViaturasRoute: typeof AuthenticatedViaturasRoute
  AuthenticatedImprimirIdRoute: typeof AuthenticatedImprimirIdRoute
  AuthenticatedOcorrenciasIdRoute: typeof AuthenticatedOcorrenciasIdRoute
  AuthenticatedOcorrenciasNovaRoute: typeof AuthenticatedOcorrenciasNovaRoute
  AuthenticatedPlantaoRoute: typeof AuthenticatedPlantaoRoute
  AuthenticatedItensArmasRoute: typeof AuthenticatedItensArmasRoute
  AuthenticatedItensRadiosRoute: typeof AuthenticatedItensRadiosRoute
  AuthenticatedItensCadRoute: typeof AuthenticatedItensCadRoute
  AuthenticatedPlantaoIdRoute: typeof AuthenticatedPlantaoIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedEscalasRoute: AuthenticatedEscalasRoute,
  AuthenticatedEquipeRoute: AuthenticatedEquipeRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedPostosRoute: AuthenticatedPostosRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedViaturasRoute: AuthenticatedViaturasRoute,
  AuthenticatedImprimirIdRoute: AuthenticatedImprimirIdRoute,
  AuthenticatedOcorrenciasIdRoute: AuthenticatedOcorrenciasIdRoute,
  AuthenticatedOcorrenciasNovaRoute: AuthenticatedOcorrenciasNovaRoute,
  AuthenticatedPlantaoRoute: AuthenticatedPlantaoRoute,
  AuthenticatedItensArmasRoute: AuthenticatedItensArmasRoute,
  AuthenticatedItensRadiosRoute: AuthenticatedItensRadiosRoute,
  AuthenticatedItensCadRoute: AuthenticatedItensCadRoute,
  AuthenticatedPlantaoIdRoute: AuthenticatedPlantaoIdRoute,
  AuthenticatedRelatorioPdfIdRoute: AuthenticatedRelatorioPdfIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
